// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using urun.Models;

#nullable disable

namespace urun.Migrations
{
    [DbContext(typeof(kitapContext))]
    partial class kitapContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("urun.Models.Kitaplar", b =>
                {
                    b.Property<int>("kitapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("kategoriID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("kitapAciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("kitapAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("kitapFiyat")
                        .HasColumnType("REAL");

                    b.Property<string>("kitapResim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("kitapStok")
                        .HasColumnType("INTEGER");

                    b.HasKey("kitapID");

                    b.ToTable("kitaplistesi");
                });
#pragma warning restore 612, 618
        }
    }
}
